- data/translations/crow_zh.ts
add zh (Simplified Chinese) translation
Signed-off-by: Bruce Zhang <zttt183525594@gmail.com>
> Add simplified chinese (zh_CN) localization

- data/translations/crow_pl.ts
> polish translation update

- crow-translate.pro
replace old `lrelease` with newer `lrelease-qt5`
> replace lrelease with lrelease-qt5

- crow-translate.pro
- data/icons/flags/my.svg
- data/resources.qrc
- data/translations/crow_ms_MY.ts
- src/langbuttongroup.cpp
- src/settings/settingsdialog.cpp
- Add Malay translation
- Fix wrong flag icon for Malay language
Hope this helps.
> Add Malay (ms-MY) localization and fix wrong flag icon

- dist/unix/create-package.sh
The $ID is defined as "manjaro" in Manjaro
> Change os-release check for manjaro

- src/mainwindow.cpp
Replace `QNetworkProxy::DefaultProxy` with `QNetworkProxy::NoProxy` for "Use system settings" and remove "Don't use a proxy".
> Fix proxy type settings

- CMakeLists.txt
- data/icons/we10x.qrc
- src/contextmenu.cpp
- src/contextmenu.h
- src/mainwindow.cpp
- src/mainwindow.h
- src/sourcetextedit.cpp
- src/sourcetextedit.h
- src/translationedit.cpp
i fixed your suggestions from PR #294
ps: i created new PR because github closed previous #294, when i moved my commits to branch and updated master from your repo :(
> Add "Search on Forvo" action to source text context menu

- CMakeLists.txt
- data/io.crow_translate.CrowTranslate.desktop
* [Finnish translation](https://crowdin.com/project/crow-translate) is already done (98%), but still missing from installation
* Translate .desktop file
> Enable Finnish localization

- data/translations/crow-translate_zh_TW.ts
language code: zh_TW
flag: Taiwan (Official nation name is Republic of China, and WE ARE NOT PART OF CHINA)
(Reference: https://en.wikipedia.org/wiki/Flag_of_the_Republic_of_China)
> Traditional Chinese translation for v2.8.7

- data/translations/crow-translate_hi_IN.ts
fixed a minor mistake in translation
> Fixed minor mistake in Hindi localization

- CMakeLists.txt
- data/io.crow_translate.CrowTranslate.metainfo.xml
Metadata useful for Linux repositories, and mandatory for Flathub.
> Add and install metainfo.xml

- src/settings/settingsdialog.cpp
From https://github.com/crow-translate/crow-translate/pull/431#issuecomment-1126811787
> Close settings window after all settings applied

- .clang-tidy
- src/cli.cpp
> Respect URL settings in CLI

- src/translationedit.cpp
> Fix popup window doesn't not displaying text, if text contains special UTF-8 symbols

- src/translationedit.cpp
> Fix regression introduced in 7e64d2c

- data/io.crow_translate.CrowTranslate.desktop
* Add Portuguese (**PT**) translation to .desktop file
* Sort languages alphabetically
> Add Portuguese translation

- .github/workflows/main.yml
- .github/workflows/release.yml
- src/mainwindow.cpp
- vcpkg.json
resolves https://github.com/crow-translate/crow-translate/issues/528
> autoselect source text when showing main window

- src/settings/autostartmanager/abstractautostartmanager.cpp
Reference: https://github.com/crow-translate/crow-translate/issues/621
> Fix settings dialog on FreeBSD

- README.md
How to translate selected text in wayland addition.
> Update README.md: How to translate selected text in Wayland.

- .clang-tidy
- .github/workflows/main.yml
- CMakeLists.txt
- data/io.crow_translate.CrowTranslate.desktop.in
- vcpkg.json
> Don't assume qdbus is in PATH

- .github/workflows/main.yml
To embed icons into build artifacts.
> Install icoutils on Windows even on main workflow
