crow-translate/crow-translate

crow-translate.pro

Many Linux distributions install it as lrelease-qt5.

Use qtPrepareTool to find proper lrelease

---

src/mainwindow.cpp

This allows user to start enter text immediately after opening crow window. Currently previous focused element is remembered.

Autofocus source text when main window is shown

---

dist/unix/create-package.sh

Don't allow script to continue execution, when apt can't install app necessary packages.

Fix create-package.sh behavior

---

src/mainwindow.cpp

raise() will set focus on it own on the first element, so focus on any widget before raise() will not work. This PR swap ui->sourceEdit->setFocus() and raise() to fix this.

Fix focus on input field when main window activates

---

README.md
src/mainwindow.cpp
src/mainwindow.h
src/mainwindow.ui

Closes #168.
I'm not familiar with Qt or C++ in general, but I've tested this and it appears to work fine. Question about the desktop file. Is the goal to provide actions for the most frequently used commands or for all of them? If it's the latter I can add a commit including a command for `swapLanguages` as well as `quit` which is currently missing in the desktop file.

Enable swapping languages from D-Bus

---

data/translations/crow-translate.ts
data/translations/crow-translate_zh_CN.ts
src/mainwindow.cpp
src/mainwindow.h
src/settings/appsettings.h
src/settings/settingsdialog.ui

Hello, thank you very much for writing such a good tool.
I have been using i3-wm under Linux, but when I use crow, the main translation window that pops up often changes the layout of opened applications. So, I've always wanted crow to have a function to display translation results based on system notification. I added some code on the basis of the program and wrote a demo. I don't know if this can be useful or if you have plans to add it. Please feel free to choose whether to use it or not. I'm a new QT player, so I don't know if there's a better way.

Translation mode: Add Notification mode

---

src/mainwindow.cpp
src/mainwindow.h
src/settings/appsettings.cpp
src/settings/appsettings.h
src/settings/settingsdialog.cpp
src/settings/settingsdialog.h
src/settings/settingsdialog.ui
src/trayicon.cpp
src/trayicon.h

I have implemented the setting of `translation notification display time`. I changed the page layout in `Setting -> Interface`. If you are not satisfied, you can adjust it or give me feedback. I don't know about the update operation of  `.ts` files so I leaved them to you. I'm very glad to be able to help with this project :).

Settings: Added 'translation notification display time' setting

---

src/ocr/ocr.cpp
src/ocr/ocr.h
src/settings/settingsdialog.cpp

The first commit makes tesseract read from a config file. The following parameters are of particular interest for CJK languages, especially when written vertically. Unfortunately automatic script and orientation detection is only supported by the legacy engine. The newer LSTM models usually give better results but require manually specifying the orientation.
```ini
tessedit_pageseg_mode
preserve_interword_spaces
paragraph_text_based
textord_old_baselines
lstm_use_matrix
```
I've been experimenting with the in development tesseract v5 on my system, so the second commit makes crow compile with it. The v5 API is still very much a moving target, so you might prefer to wait for a stable release first. That being said, it isn't too bad since crowing is only using a small subset of the API. …

Improve OCR

---

CMakeLists.txt
src/ocr/ocr.cpp
src/settings/appsettings.cpp
src/settings/appsettings.h
src/settings/settingsdialog.cpp
src/settings/settingsdialog.h
src/settings/settingsdialog.ui
src/settings/tesseractparameterstablewidget.cpp
src/settings/tesseractparameterstablewidget.h

This adds the parameter table for tesseract discussed in #233. The first three commits implement the editing, saving, and loading functionality and deal with any invalid rows in the table by silently dropping them before returning the parameters.
The fourth commit adds a validation layer that displays a message and focuses the first invalid cell. It works, but I'm not sure if there's a better way to organize the code for it.

Tesseract parameters

---

.github/workflows/main.yml
README.md
src/main.cpp
src/mainwindow.cpp
src/mainwindow.h
src/ocr/ocr.cpp
src/ocr/ocr.h

@LiteracyFanatic, could you check if it works for you? But you need an application that supports QVariantMap. For example, `dbus-send` and `qdbus` do not support this, but `gdbus` can:
```bash
gdbus call --session -d io.crow_translate.CrowTranslate -o /io/crow_translate/CrowTranslate/Ocr -m io.crow_translate.CrowTranslate.Ocr.setParameters "{'name': <'value'>}"
```

Add the ability to change Tesseract parameters via D-Bus

---

src/mainwindow.cpp

This pull request fix XFWM behaviour. Now clicking by tray icon open Crow window on any workplace, even if it was opened on another workplace. Hopefully fixes #342.

Fix XFWM behaviour

---

src/ocr/screengrabbers/waylandplasmascreengrabber.cpp

When building on void/x86_64/linux-musl/wayland, I got this:
`
/working/dictionary_and_thesaurus/crow-translate/src/ocr/screengrabbers/waylandplasmascreengrabber.cpp:92:5: error: unknown type name 'fd_set'
fd_set readset;
`
`
/working/dictionary_and_thesaurus/crow-translate/src/ocr/screengrabbers/waylandplasmascreengrabber.cpp:95:5: error: unknown type name 'timeval'
timeval timeout{30, 0};
`
`
/working/dictionary_and_thesaurus/crow-translate/src/ocr/screengrabbers/waylandplasmascreengrabber.cpp:102:34: error: use of undeclared identifier 'FD_SETSIZE'
const int ready = select(FD_SETSIZE, &readset, nullptr, nullptr, &timeout);
`
In waylandplasmascreengrabber.cpp, I added
`
#include <sys/select.h>
`
Build  succeeded.

#include <sys/select.h> to waylandplasmascreengrabber.cpp

---

data/io.crow_translate.CrowTranslate.metainfo.xml

This should help Linux store frontends to determine what languages the app is translated to.

Add translations element to metainfo

---

CMakeLists.txt
src/ocr/screengrabbers/waylandportalscreengrabber.cpp
src/settings/autostartmanager/portalautostartmanager.cpp
src/xdgdesktopportal.cpp
src/xdgdesktopportal.h

Follow-up from https://github.com/crow-translate/crow-translate/pull/429#issuecomment-1126707432, attempt to fix #430
It doesn't crash anymore even if we don't check if the active window isn't `nullptr`, but I'm still not sure if this way to determine `parent_window` ID for XDP is correct. Looks like it is for X11, but not for Wayland.

Retrieve parent window ID for XDG desktop portal dialogs

---

data/translations/crow-translate_pt_PT.ts

Portuguese European (**pt-PT)** is different from Portuguese Brazilian (**pt-BR**). I noticed that only pt-BR existed, so I did a pt-PT translation.
**NOTE:** As is stands, (before this commit, see attached pic), the Portuguese flag is (wrongly) corresponding to the only existing until now Portuguese BR, so if you agree to add my pt-PT translation, you should change it to the Brazilian flag...
In the end the correct standard is: **Portuguese** pt-PT (Portuguese flag) ; **Portuguese Brazilian** pt-BR (Brazilian flag).
Best regards
Ricardo Simões
xmcorporation.com

Portuguese European pt-PT translatio complete

---

.github/workflows/release.yml
cmake/AppImage.cmake

This is done by embedding update information inside the AppImage itself, which for linuxdeploy can be done using the `UPDATE_INFORMATION` variable as described in the [AppImage documentation](https://docs.appimage.org/packaging-guide/optional/updates.html#using-linuxdeploy).
Thus, this adds a `.zsync` file to the release section, which makes it easier to update to newer versions without re-installing the whole file using tools like [AppImageUpdate](https://github.com/AppImage/AppImageUpdate).
To test this, first install [appimageupdatetool](https://github.com/AppImage/AppImageUpdate/releases), and make it executable, then install this version of [Crow_Translate-2.9.12-x86_64.AppImage](https://github.com/eljamm/crow-translate/releases/download/2.9.12/Crow_Translate-2.9.12-x86_64.AppImage). …

Make AppImages updateable

---

src/mainwindow.cpp
src/settings/appsettings.cpp
src/settings/appsettings.h
src/settings/settingsdialog.cpp
src/settings/settingsdialog.h
src/settings/settingsdialog.ui
src/speakbuttons.cpp
src/speakbuttons.h

~~There's still a bug actually, and I cannot determine how the hell it got there:~~
~~In `SettingsDialog::loadSettings` TTS region preferences are successfully loaded, but when `SettingsDialog::onGoogleLanguageSelectionChanged` is reached, the country for currently selected language is strangely reset to `QLocale::AnyCountry`.~~
~~So, even if you have set the region for, say, English to United Kingdom previously, when you open settings again it still says "Default region".~~
~~I've left two `qDebugs` in the function in question.~~
Fixed

Added an option to select regional voice for Google

---

src/ocr/ocr.cpp

Fix two warning generated by newer (?) clang:
1. std::vector::size returns unsigned long, but QList::reserve has an int argument; solution: using static_cast<int>
2. Use range-based for loop instead of old-style for (int i = 0; ...)

Fix warning generated by clang in OCR module

---

data/icons/flags.qrc
src/languagebuttonswidget.cpp

As in title.
https://github.com/HatScripts/circle-flags.git was updated to 2.4.1 since uyghur flag is only available after 2.4.0.

Correct flags of Hong Kong, Taiwan, and Uyghur for Cantonese, Chinese (Traditional), and Uighur

---

.github/workflows/main.yml

Because VCPKG have issue with bundling dlls for debug builds.

Build release in main workflow

---

src/settings/appsettings.h
src/settings/settingsdialog.cpp

Read settings from application directory when building in portable mode

---

src/settings/appsettings.cpp
src/settings/appsettings.h

This will fix #550 because static initilization happend before main() and initializtion of QApplication, therefore applicationDirPath() return empty string.

Remove static from s_portableConfigName initialization

---

src/settings/appsettings.cpp
src/settings/settingsdialog.ui

Official https://lingva.ml/ instance replaced with https://lingva.garudalinux.org/ (garuda linux instance)
fix: https://github.com/crow-translate/QOnlineTranslator/issues/60

Fix lingva.ml site offline

---

src/settings/settingsdialog.ui

**Lingva**
Added: https://lingva.ml (works correctly again), https://translate.plausibility.cloud and https://lingva.lunar.icu.
Removed:
https://lingva.garudalinux.org now required some cloudflare BS, proof: https://lingva.garudalinux.org/api/v1/en/ru/test (see the package cookies).
https://translate.alefvanoon.xyz and https://translate.igna.rocks domains were unpaid.
**LibreTranslate**
https://libretranslate.de still works, slowly.
Removed:
https://translate.mentality.rip and https://translate.astian.org were removed, because they doesn't work anymore.
https://translate.argosopentech.com subdomain and their examples doesn't work anymore but you can still access https://argosopentech.com

Add new and remove broken Libre and Lingva instances
